#!/usr/bin/env node
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { writeFileSync } from 'node:fs';

function arg(name, fallback = ''){
  const i = process.argv.indexOf(name);
  if(i === -1) return fallback;
  return process.argv[i + 1] ?? fallback;
}

function intArg(name, fallback){
  const raw = arg(name, '');
  if(!raw) return fallback;
  const n = Number(raw);
  if(!Number.isFinite(n)) return fallback;
  return Math.floor(n);
}

function upperSafe(str){
  return String(str || '').toUpperCase().replace(/[^A-Z0-9]/g, '');
}

function randomToken(len){
  const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const bytes = randomBytes(len);
  let out = '';
  for(let i = 0; i < len; i++){
    out += alphabet[bytes[i] % alphabet.length];
  }
  return out;
}

function formatKey(prefix){
  return `${prefix}-${randomToken(4)}-${randomToken(4)}-${randomToken(4)}`;
}

function sha256Hex(input){
  return createHash('sha256').update(input).digest('hex');
}

function csvEscape(v){
  const s = String(v ?? '');
  if(/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function sqlEscape(v){
  return String(v ?? '').replace(/'/g, "''");
}

const count = intArg('--count', 100);
const start = intArg('--start', 1);
const years = Number(arg('--years', '1')) || 1;
const maxDevices = intArg('--max-devices', 2);
const prefix = upperSafe(arg('--prefix', 'HORD'));
const productId = String(arg('--product', 'hord.vocabmaster.chrome')).trim();
const plan = String(arg('--plan', 'pro_annual')).trim();
const salt = String(arg('--salt', '')).trim();
const outSql = String(arg('--out-sql', '/tmp/licenses_batch.sql')).trim();
const outCsv = String(arg('--out-csv', '/tmp/licenses_batch.csv')).trim();

if(!salt){
  console.error('Missing required --salt');
  console.error('Example: node scripts/gen_license_batch.mjs --salt "99999999"');
  process.exit(1);
}
if(!prefix){
  console.error('Invalid --prefix');
  process.exit(1);
}
if(count <= 0){
  console.error('--count must be > 0');
  process.exit(1);
}

const now = Date.now();
const expiresAt = now + Math.floor(years * 365 * 24 * 60 * 60 * 1000);
const entitlements = {
  word_limit: -1,
  note_limit: -1,
  import_export: true,
  bulk_edit: true,
  review_mode: 'advanced',
  quote_export_enabled: true,
  quote_templates: ['light', 'dark', 'hordSignature', 'editorial', 'gradientSoft', 'boldImpact'],
  quote_advanced_settings: true,
};
const entitlementsJson = JSON.stringify(entitlements);

const rows = [];
const usedKeys = new Set();
for(let i = 0; i < count; i++){
  let key = '';
  do { key = formatKey(prefix); } while(usedKeys.has(key));
  usedKeys.add(key);

  const idx = start + i;
  const licenseId = `lic_${String(idx).padStart(6, '0')}_${randomUUID().replace(/-/g, '').slice(0, 8)}`;
  const keyHash = sha256Hex(`${salt}|${key}`);
  rows.push({
    idx,
    licenseId,
    key,
    keyHash,
    status: 'active',
  });
}

const sqlLines = [];
sqlLines.push('-- Generated by scripts/gen_license_batch.mjs');
sqlLines.push(`-- count: ${count}, prefix: ${prefix}, plan: ${plan}, product: ${productId}`);
sqlLines.push(`-- generated_at: ${new Date(now).toISOString()}`);
sqlLines.push('');
for(const r of rows){
  sqlLines.push(
`INSERT INTO licenses (
  id,
  product_id,
  license_key_hash,
  plan,
  status,
  issued_at,
  expires_at,
  max_devices,
  entitlements_json,
  created_at,
  updated_at
) VALUES (
  '${sqlEscape(r.licenseId)}',
  '${sqlEscape(productId)}',
  '${sqlEscape(r.keyHash)}',
  '${sqlEscape(plan)}',
  'active',
  ${now},
  ${expiresAt},
  ${maxDevices},
  '${sqlEscape(entitlementsJson)}',
  ${now},
  ${now}
);`
  );
}

const csvHeader = [
  'index',
  'license_id',
  'license_key',
  'license_key_hash',
  'product_id',
  'plan',
  'status',
  'issued_at',
  'expires_at',
  'max_devices',
].join(',');

const csvRows = rows.map((r)=>[
  r.idx,
  r.licenseId,
  r.key,
  r.keyHash,
  productId,
  plan,
  'active',
  now,
  expiresAt,
  maxDevices,
].map(csvEscape).join(','));

writeFileSync(outSql, `${sqlLines.join('\n')}\n`, 'utf8');
writeFileSync(outCsv, `${csvHeader}\n${csvRows.join('\n')}\n`, 'utf8');

console.log(`Generated ${count} licenses.`);
console.log(`SQL: ${outSql}`);
console.log(`CSV: ${outCsv}`);
console.log(`Example key: ${rows[0]?.key || ''}`);
console.log(`Expires at: ${new Date(expiresAt).toISOString()}`);
